### ISSUE TITLE
Servicebus example

### ISSUE THREAD

**Issue by vincentvanderwalt** [aspnet/SignalR-ServiceBus#7]
Hi I'm trying to migrate an application using signalr servicebus technology pre asp.net 5.

I can't find an example of how to use the new servicebus class like most of the .net in here have.

Can someone point me to an example of hooking up service bus ?

Thanks

**Comment by muratg** [comment]
Are you trying to use SignalR 2.x with ASP.NET 5? Or something else?

**Comment by vincentvanderwalt** [comment]
I'm trying to use version 3 beta3 with azure servicebus backplane.

But can't find an example of how to do it.

In pre vnext it was fairly easy but I couldn't work it out even with looking at the test project.

Most ASP.net 5 projects have good samples. The servicebus doesn't. Hence raising this issue.

-----Original Message-----

**Comment by BrennanConroy** [comment]
That's because this version of ServiceBus doesn't even have an alpha. There is no released package yet, sorry.

**Comment by vincentvanderwalt** [comment]
No worries.

I'll build the new version of our software using a non clustered setup. That means it'll work with signalr as it stands.

I'll then implement servicebus version when it's available.

Thanks for the replies

Vinny

-----Original Message-----

**Comment by martinstenhoff** [comment]
What's the status of the "Microsoft.AspNetCore.SignalR.ServiceBus": "0.1.0-rtm-21431" package, is it in any workable state (using net 4.6.1 full framework)?

I tried adding in ServiceBus using:

```
services.AddServiceBus(options =>
{
    options.ConnectionString = "<MyAzureServiceBusConnectionString>";
    options.TopicPrefix = "MyApp";
});
```

But then no messages gets delivered. SignalR on its own works, but not with ServiceBus backplane.

Perhaps this is due to conflicting ServiceBus versions as we are already using "WindowsAzure.ServiceBus": "3.3.2" and not the 2.5.4 version specified by SignalR-ServiceBus.

**Comment by moozzyk** [comment]
@martinstenhoff - it is likely the version mismatch. It was already reported for the 2.x version of SignalR (https://github.com/SignalR/SignalR/issues/3548). We are considering changes to scale-out model in SignalR vNext and because the plans in this area are not finalized no actual work was done here.
